version: "3.8"

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    networks:
      - bot-network

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sui_whale_bot}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bot-network

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis-data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
